module.exports = {
  "mysql":{
    "host":"127.0.0.1",
    "port":3306,
    "user":"user",
    "password":"pass",
    "database":"event"
  },
  "mysql_api":{
    "host":"127.0.0.1",
    "port":3306,
    "user":"root",
    "password":"",
    "database":"event_api"
  },
  "app":{
    "listen_port":8080
  }
};